#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
require File.dirname(__FILE__)+'/../config/environment'
ActionMailer::Base.raise_delivery_errors = false
ActionMailer::Base.delivery_method = :test

# arguments

login_name = ARGV[0]
email = ARGV[1]
password = ARGV[2]

if User.find_by_email(email)
  puts "The email is already used."
  exit(1)
end

user = User.new :password => password, :password_confirmation => password, :email => email, :terms_of_use => '1'
user.login = login_name.dup
user.is_admin = false
if user.save
  user.activate
  #puts "User #{email} created successfully."
else
  puts "Failed creating user #{email}."
  exit(1)
end


# print the user ID so the caller can use it.
puts user.id
